apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ca
  namespace: istio-system
spec:
  secretName: istio-ca-key-pair
  duration: 17520h # 2 years
  commonName: istio-ca
  isCA: true
  usages:
    - digital signature
    - key encipherment
    - cert sign
  dnsNames:
    - istio-ca
  issuerRef:
    name: istio-aws-pca-issuer
    kind: AWSPCAClusterIssuer
    group: awspca.cert-manager.io