apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: demo-app
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: demo-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-app-ingress
  namespace: demo-app
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: aws-pca-cluster-issuer
    cert-manager.io/common-name: ${LOAD_BALANCER_HOSTNAME}
    cert-manager.io/duration: 2160h
    cert-manager.io/renew-before: 360h
spec:
  tls:
  - hosts:
    - ${LOAD_BALANCER_HOSTNAME}
    secretName: demo-app-tls
  rules:
  - host: ${LOAD_BALANCER_HOSTNAME}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-app
            port:
              number: 80