apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hello-cert
  namespace: istio-system
spec:
  secretName: hello-tls-secret
  duration: 8760h # 1 year
  renewBefore: 360h # 15 days
  commonName: hello.example.com
  dnsNames:
  - hello.example.com
  issuerRef:
    name: aws-pca-cluster-issuer
    kind: AWSPCAClusterIssuer
    group: awspca.cert-manager.io