apiVersion: v1
kind: ServiceAccount
metadata:
  name: spiffe-csi-driver
  namespace: spiffe-csi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spiffe-csi-driver
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spiffe-csi-driver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spiffe-csi-driver
subjects:
- kind: ServiceAccount
  name: spiffe-csi-driver
  namespace: spiffe-csi
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.spiffe.io
spec:
  podInfoOnMount: true
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spiffe-csi-driver
  namespace: spiffe-csi
spec:
  selector:
    matchLabels:
      app: spiffe-csi-driver
  template:
    metadata:
      labels:
        app: spiffe-csi-driver
    spec:
      serviceAccountName: spiffe-csi-driver
      containers:
      - name: spiffe-csi-driver
        image: ghcr.io/spiffe/spiffe-csi-driver:1.3.0
        args:
        - --node-id=$(NODE_ID)
        - --workload-api-socket-path=/run/spire/sockets/agent.sock
        env:
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          privileged: true
        volumeMounts:
        - name: kubelet-dir
          mountPath: /var/lib/kubelet
          mountPropagation: Bidirectional
        - name: spire-socket
          mountPath: /run/spire/sockets
          readOnly: true
      volumes:
      - name: kubelet-dir
        hostPath:
          path: /var/lib/kubelet
      - name: spire-socket
        hostPath:
          path: /run/spire/sockets